server:
  port: ${SERVER_PORT:8080}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:6401/db_kap_server}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  secret-key: ${SECRET_KEY}