server:
  port: ${SERVER_PORT:8080}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:6401/db_ovesdu_server}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true